# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'takasla' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # Add vector icons fonts to Info.plist
    installer.pods_project.targets.each do |target|
      if target.name == 'RCT-Folly'
        target.build_phases.each do |phase|
          if phase.display_name == '[CP-User] Copy PodHelpers Scripts'
            phase.show_env_vars = false
          end
        end
      end
    end

    # Link vector-icons fonts
    project = installer.pods_project
    project.targets.each do |target|
      if target.name == 'react-native-vector-icons'
        phase = target.source_build_phase
        phase.files.each do |build_file|
          ref = build_file.file_ref
          if ref.real_path.to_s.include?('Fonts')
            build_file.settings = { 'COMPASS_IMPORTS' => '**/*.ttf' }
          end
        end
      end
    end
  end
end
